In [78]:
import pandas as pd 
from pathlib import Path
import re 
import json

In [145]:
p = Path("/home/finn/workspace/creatures/logs/simulation_1782562429.log")
assert p.exists()

In [146]:
with open(p, "r") as f:
    lines = f.readlines()

print(len(lines))

6356

In [152]:
def extract_animal_data(line):
    m = re.match(
        r".*animal_despawn,reason=(?P<reason>.*),spawn_at_frame=(?P<spawn_at>.*),despawn_at_frame=(?P<despawn_at>.*),lifetime_frames=(?P<lifetime>.*),genome=(?P<genome>.*),diet=(?P<diet>.*),family=(?P<family>.*).*",
        line,
    )

    if m is not None:
        d = {}
        d["reason"] = m.group("reason")
        d["spawn_at"] = float(m.group("spawn_at"))
        d["despawn_at"] = float(m.group("despawn_at"))
        d["lifetime"] = float(m.group("lifetime"))
        d["genome"] = m.group("genome")
        d["diet"] = m.group("diet")
        d["family"] = int(m.group("family"))
        return d
    return None

In [153]:
df = pd.DataFrame(list(filter(None, map(extract_animal_data, lines))))
df

,reason,spawn_at,despawn_at,lifetime,genome,diet,family
0,starvation,325.0,788.0,463.0,"[-0.4915266, 0.6011691, -0.7362821, 0.09686971...",Omnivore,1893112597
1,starvation,0.0,822.0,822.0,"[-0.38813543, 0.8613992, 0.76623106, 0.3038671...",Omnivore,0
2,starvation,3.0,1066.0,1063.0,"[-0.09095931, 0.27592206, 0.568655, 0.56266594...",Carnivore,3652179443
3,starvation,999.0,1100.0,101.0,"[-0.71127844, 0.19468808, -0.20717192, -0.6587...",Carnivore,4026671404
4,starvation,1827.0,1977.0,150.0,"[-0.77485394, -0.7612109, -0.14076996, -0.8585...",Carnivore,3397224529
...,...,...,...,...,...,...,...
1344,starvation,11271.0,13942.0,2671.0,"[-0.24221337, -1.0015653, 0.12837479, 0.965032...",Herbivore,1331140635
1345,starvation,13535.0,13958.0,423.0,"[-0.26142493, -1.05282, 0.21793394, 0.9443599,...",Herbivore,1331140635
1346,starvation,13535.0,13977.0,442.0,"[-0.2705557, -1.0421623, 0.22780831, 0.9422958...",Herbivore,1331140635
1347,starvation,12683.0,13979.0,1296.0,"[-0.46071213, -1.0591824, -0.07347073, 0.87462...",Herbivore,1331140635
1348,starvation,13138.0,13997.0,859.0,"[-0.2548722, -1.039563, 0.13032077, 0.92882943...",Herbivore,1331140635

In [154]:
df.groupby("reason").count()

            spawn_at  despawn_at  lifetime  genome  diet  family
reason
starvation      1349        1349      1349    1349  1349    1349

In [143]:
def extract_population_data(line):
    m = re.match(
        r".*frame=(?P<frame>d*).*population_size plants=(?P<n_plants>.*) animals=AnimalPopulation (?P<json>\{.*\}).*",
        line,
    )
    if m is not None:
        d = {}
        #d["frame"] = int(m.group("frame"))
        d["n_plants"] = int(m.group("n_plants"))
        json_data = json.loads(m.group("json"))
        d["carnivores"] = int(json_data.get("carnivores", 0))
        d["herbivores"] = int(json_data.get("herbivores", 0))
        d["omnivores"] = int(json_data.get("omnivores", 0))
        return d
    return m

In [144]:
df = pd.DataFrame(list(filter(None, map(extract_population_data, lines))))
df

JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

In [ ]:
2026-06-27T09:42:30.541231Z  INFO bevy_project::logging: [frame=1301] population_size plants=43 animals=AnimalPopulation { carnivores: 1, herbivores: 12, omnivores: 0 }